name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: apt-get install readline
        run: sudo apt-get install libreadline6-dev
      - name: apt-get install libgtest-dev
        run: sudo apt-get install libgtest-dev
      - name: cmake
        run: cmake -S . -B build && cmake --build build -j4
      - name: test
        run: cd build && ctest
      - name: make install
        run: cd build && sudo make install
      - name: run example
        run: cd example && bash test.sh
