name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: apt-get install readline
        run: sudo apt-get install libreadline6-dev
      - name: apt-get install libgtest-dev
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make install
      - name: make test
        run: make test
      - name: make install
        run: mkdir build && cd build && cmake .. && sudo make install
      - name: run example
        run: cd example && bash test.sh
